// Human persona data for agent resume cards
// Maps agent slugs to human-like profile information

export interface AgentPersona {
  humanName: string;
  title: string;
  photoUrl: string;
  yearsExp: number;
  rating: number;
  specialties: string[];
  tasksLabel: string;
}

const PERSONAS: Record<string, AgentPersona> = {
  // ── Product & Engineering ─────────────────────────────
  "startup-idea-gen": {
    humanName: "Arjun Patel",
    title: "Startup Ideation Specialist",
    photoUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=startup-idea-gen",
    yearsExp: 9,
    rating: 4.9,
    specialties: ["Ideation", "Market Fit", "Pitch Decks"],
    tasksLabel: "2.1k tasks",
  },
  "product-launch": {
    humanName: "Sofia Martinez",
    title: "Product Launch Strategist",
    photoUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=product-launch",
    yearsExp: 11,
    rating: 4.9,
    specialties: ["Go-to-Market", "Launch Plans", "Growth"],
    tasksLabel: "1.9k tasks",
  },
  "system-architect": {
    humanName: "Hiroshi Tanaka",
    title: "Systems Architecture Lead",
    photoUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=system-architect",
    yearsExp: 12,
    rating: 5.0,
    specialties: ["Architecture", "Scalability", "Cloud"],
    tasksLabel: "3.2k tasks",
  },
  "ux-designer": {
    humanName: "Amara Osei",
    title: "UX Design Expert",
    photoUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=ux-designer",
    yearsExp: 8,
    rating: 4.9,
    specialties: ["User Research", "Prototyping", "Design Systems"],
    tasksLabel: "2.4k tasks",
  },
  "fullstack-developer": {
    humanName: "Liam Chen",
    title: "Full-Stack Developer",
    photoUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=fullstack-developer",
    yearsExp: 10,
    rating: 4.9,
    specialties: ["React", "Node.js", "TypeScript"],
    tasksLabel: "4.1k tasks",
  },
  "python-expert": {
    humanName: "Fatima Al-Rashid",
    title: "Python Engineering Specialist",
    photoUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=python-expert",
    yearsExp: 9,
    rating: 4.8,
    specialties: ["Python", "Data Pipelines", "Automation"],
    tasksLabel: "3.5k tasks",
  },
  "code-reviewer": {
    humanName: "Marcus Johnson",
    title: "Code Quality Analyst",
    photoUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=code-reviewer",
    yearsExp: 11,
    rating: 4.9,
    specialties: ["Code Review", "Best Practices", "Security"],
    tasksLabel: "5.2k tasks",
  },
  "debugger": {
    humanName: "Yuki Nakamura",
    title: "Debugging Specialist",
    photoUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=debugger",
    yearsExp: 7,
    rating: 4.8,
    specialties: ["Debugging", "Performance", "Root Cause"],
    tasksLabel: "2.8k tasks",
  },
  "sprint-planner": {
    humanName: "Elena Kowalski",
    title: "Agile Sprint Planner",
    photoUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=sprint-planner",
    yearsExp: 8,
    rating: 4.8,
    specialties: ["Scrum", "Sprint Planning", "Velocity"],
    tasksLabel: "1.6k tasks",
  },
  "project-planner": {
    humanName: "David Okonkwo",
    title: "Project Management Lead",
    photoUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=project-planner",
    yearsExp: 10,
    rating: 4.9,
    specialties: ["Roadmaps", "Resource Planning", "Delivery"],
    tasksLabel: "2.3k tasks",
  },
  "home-renovation": {
    humanName: "Isabella Torres",
    title: "Home Renovation Advisor",
    photoUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=home-renovation",
    yearsExp: 6,
    rating: 4.7,
    specialties: ["Interior Design", "Budgeting", "Contractors"],
    tasksLabel: "890 tasks",
  },
  "game-design": {
    humanName: "Kai Svensson",
    title: "Game Design Specialist",
    photoUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=game-design",
    yearsExp: 7,
    rating: 4.8,
    specialties: ["Game Mechanics", "Level Design", "Balancing"],
    tasksLabel: "1.2k tasks",
  },
  "ui-ux-feedback": {
    humanName: "Priya Sharma",
    title: "UI/UX Feedback Analyst",
    photoUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=ui-ux-feedback",
    yearsExp: 6,
    rating: 4.8,
    specialties: ["Usability", "Heuristics", "A/B Testing"],
    tasksLabel: "1.5k tasks",
  },
  "devops-agent": {
    humanName: "Omar Hassan",
    title: "DevOps Engineer",
    photoUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=devops-agent",
    yearsExp: 9,
    rating: 4.9,
    specialties: ["CI/CD", "Docker", "Kubernetes"],
    tasksLabel: "2.7k tasks",
  },

  // ── Research & Intelligence ───────────────────────────
  "deep-research": {
    humanName: "Dr. Mei Lin",
    title: "Deep Research Analyst",
    photoUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=deep-research",
    yearsExp: 12,
    rating: 5.0,
    specialties: ["Research", "Synthesis", "Analysis"],
    tasksLabel: "3.8k tasks",
  },
  "academic-researcher": {
    humanName: "Dr. Adaeze Nwosu",
    title: "Academic Research Fellow",
    photoUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=academic-researcher",
    yearsExp: 10,
    rating: 4.9,
    specialties: ["Literature Review", "Citations", "Methodology"],
    tasksLabel: "2.1k tasks",
  },
  "fact-checker": {
    humanName: "Jonas Eriksson",
    title: "Fact-Checking Specialist",
    photoUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=fact-checker",
    yearsExp: 8,
    rating: 4.9,
    specialties: ["Verification", "Sources", "Accuracy"],
    tasksLabel: "4.3k tasks",
  },
  "startup-trends": {
    humanName: "Zara Ibrahim",
    title: "Startup Trends Analyst",
    photoUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=startup-trends",
    yearsExp: 7,
    rating: 4.8,
    specialties: ["Trend Analysis", "VC Insights", "Markets"],
    tasksLabel: "1.4k tasks",
  },
  "competitor-intel": {
    humanName: "Nikolai Volkov",
    title: "Competitive Intelligence Lead",
    photoUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=competitor-intel",
    yearsExp: 9,
    rating: 4.9,
    specialties: ["Competitor Analysis", "SWOT", "Strategy"],
    tasksLabel: "1.9k tasks",
  },
  "web-intel": {
    humanName: "Anika Gupta",
    title: "Web Intelligence Specialist",
    photoUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=web-intel",
    yearsExp: 6,
    rating: 4.7,
    specialties: ["OSINT", "Web Scraping", "Data Mining"],
    tasksLabel: "2.5k tasks",
  },
  "data-analyst": {
    humanName: "Rafael Santos",
    title: "Data Analytics Expert",
    photoUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=data-analyst",
    yearsExp: 8,
    rating: 4.9,
    specialties: ["SQL", "Statistics", "Dashboards"],
    tasksLabel: "3.1k tasks",
  },
  "visualization-expert": {
    humanName: "Ingrid Bergström",
    title: "Data Visualization Designer",
    photoUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=visualization-expert",
    yearsExp: 7,
    rating: 4.8,
    specialties: ["Charts", "Infographics", "Storytelling"],
    tasksLabel: "1.7k tasks",
  },
  "strategy-advisor": {
    humanName: "James Okafor",
    title: "Strategy Consultant",
    photoUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=strategy-advisor",
    yearsExp: 11,
    rating: 5.0,
    specialties: ["Strategy", "Frameworks", "Growth"],
    tasksLabel: "2.6k tasks",
  },
  "decision-helper": {
    humanName: "Clara Johansson",
    title: "Decision Science Specialist",
    photoUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=decision-helper",
    yearsExp: 7,
    rating: 4.8,
    specialties: ["Decision Trees", "Risk Analysis", "Pros/Cons"],
    tasksLabel: "1.3k tasks",
  },
  "vc-due-diligence": {
    humanName: "Alexander Wei",
    title: "Due Diligence Analyst",
    photoUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=vc-due-diligence",
    yearsExp: 10,
    rating: 4.9,
    specialties: ["Due Diligence", "Financials", "Term Sheets"],
    tasksLabel: "980 tasks",
  },
  "market-sizing": {
    humanName: "Nadia Petrov",
    title: "Market Sizing Specialist",
    photoUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=market-sizing",
    yearsExp: 8,
    rating: 4.8,
    specialties: ["TAM/SAM/SOM", "Sizing Models", "Research"],
    tasksLabel: "1.1k tasks",
  },

  // ── Sales & Revenue ───────────────────────────────────
  "sales-rep": {
    humanName: "Carlos Mendoza",
    title: "Sales Development Rep",
    photoUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=sales-rep",
    yearsExp: 8,
    rating: 4.8,
    specialties: ["Cold Outreach", "Pitching", "Closing"],
    tasksLabel: "3.4k tasks",
  },
  "investment-analyst": {
    humanName: "Grace Kimura",
    title: "Investment Research Analyst",
    photoUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=investment-analyst",
    yearsExp: 9,
    rating: 4.9,
    specialties: ["Equities", "Valuation", "Portfolio"],
    tasksLabel: "1.8k tasks",
  },
  "personal-finance": {
    humanName: "Kwame Asante",
    title: "Personal Finance Advisor",
    photoUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=personal-finance",
    yearsExp: 7,
    rating: 4.8,
    specialties: ["Budgeting", "Investing", "Tax Planning"],
    tasksLabel: "2.2k tasks",
  },
  "real-estate-analyst": {
    humanName: "Leila Ahmadi",
    title: "Real Estate Analyst",
    photoUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=real-estate-analyst",
    yearsExp: 8,
    rating: 4.8,
    specialties: ["Property Analysis", "Market Trends", "ROI"],
    tasksLabel: "1.1k tasks",
  },
  "pricing-strategist": {
    humanName: "Henrik Larsen",
    title: "Pricing Strategy Expert",
    photoUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=pricing-strategist",
    yearsExp: 9,
    rating: 4.9,
    specialties: ["Pricing Models", "Revenue Ops", "Margins"],
    tasksLabel: "940 tasks",
  },
  "proposal-writer": {
    humanName: "Thandiwe Moyo",
    title: "Proposal Writing Specialist",
    photoUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=proposal-writer",
    yearsExp: 7,
    rating: 4.8,
    specialties: ["RFPs", "Business Proposals", "Persuasion"],
    tasksLabel: "1.6k tasks",
  },

  // ── Marketing & Content ───────────────────────────────
  "content-creator": {
    humanName: "Maya Rivera",
    title: "Content Creation Lead",
    photoUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=content-creator",
    yearsExp: 8,
    rating: 4.9,
    specialties: ["Copywriting", "Storytelling", "Brand Voice"],
    tasksLabel: "4.7k tasks",
  },
  "linkedin-post": {
    humanName: "Daniel Achebe",
    title: "LinkedIn Content Strategist",
    photoUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=linkedin-post",
    yearsExp: 6,
    rating: 4.8,
    specialties: ["LinkedIn", "Thought Leadership", "Engagement"],
    tasksLabel: "3.2k tasks",
  },
  "blog-to-podcast": {
    humanName: "Sana Malik",
    title: "Blog-to-Podcast Producer",
    photoUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=blog-to-podcast",
    yearsExp: 5,
    rating: 4.7,
    specialties: ["Podcast Scripts", "Repurposing", "Audio"],
    tasksLabel: "780 tasks",
  },
  "journalist": {
    humanName: "Thomas Beaumont",
    title: "Investigative Journalist",
    photoUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=journalist",
    yearsExp: 10,
    rating: 4.9,
    specialties: ["Reporting", "Interviews", "Long-form"],
    tasksLabel: "1.4k tasks",
  },
  "technical-writer": {
    humanName: "Yuna Park",
    title: "Technical Writing Expert",
    photoUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=technical-writer",
    yearsExp: 8,
    rating: 4.9,
    specialties: ["Documentation", "API Docs", "Tutorials"],
    tasksLabel: "2.9k tasks",
  },
  "editor": {
    humanName: "Charlotte Duval",
    title: "Senior Editor",
    photoUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=editor",
    yearsExp: 11,
    rating: 5.0,
    specialties: ["Editing", "Style Guide", "Clarity"],
    tasksLabel: "5.1k tasks",
  },
  "email-drafter": {
    humanName: "Ahmed Benali",
    title: "Email Marketing Specialist",
    photoUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=email-drafter",
    yearsExp: 6,
    rating: 4.8,
    specialties: ["Email Campaigns", "Subject Lines", "CTAs"],
    tasksLabel: "3.6k tasks",
  },
  "meme-caption": {
    humanName: "Zoe Chang",
    title: "Meme & Caption Creator",
    photoUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=meme-caption",
    yearsExp: 4,
    rating: 4.7,
    specialties: ["Memes", "Viral Content", "Humor"],
    tasksLabel: "2.8k tasks",
  },
  "seo-agent": {
    humanName: "Viktor Novak",
    title: "SEO Optimization Expert",
    photoUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=seo-agent",
    yearsExp: 8,
    rating: 4.9,
    specialties: ["SEO", "Keywords", "Ranking Strategy"],
    tasksLabel: "2.3k tasks",
  },
  "social-media": {
    humanName: "Amira Diallo",
    title: "Social Media Strategist",
    photoUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=social-media",
    yearsExp: 7,
    rating: 4.8,
    specialties: ["Social Strategy", "Engagement", "Analytics"],
    tasksLabel: "3.9k tasks",
  },
  "ad-copy": {
    humanName: "Lucas Moreau",
    title: "Ad Copywriter",
    photoUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=ad-copy",
    yearsExp: 7,
    rating: 4.8,
    specialties: ["Ad Copy", "Headlines", "Conversion"],
    tasksLabel: "2.1k tasks",
  },
  "newsletter-agent": {
    humanName: "Rina Takahashi",
    title: "Newsletter Curator",
    photoUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=newsletter-agent",
    yearsExp: 5,
    rating: 4.7,
    specialties: ["Newsletters", "Curation", "Retention"],
    tasksLabel: "1.5k tasks",
  },
  "video-script": {
    humanName: "Mateo Vargas",
    title: "Video Script Writer",
    photoUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=video-script",
    yearsExp: 6,
    rating: 4.8,
    specialties: ["Video Scripts", "YouTube", "Hooks"],
    tasksLabel: "1.8k tasks",
  },

  // ── Operations & Productivity ─────────────────────────
  "general-assistant": {
    humanName: "Emma Lindqvist",
    title: "Executive Assistant",
    photoUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=general-assistant",
    yearsExp: 8,
    rating: 4.9,
    specialties: ["Task Management", "Research", "Writing"],
    tasksLabel: "6.2k tasks",
  },
  "meeting-notes": {
    humanName: "Samuel Mensah",
    title: "Meeting Notes Specialist",
    photoUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=meeting-notes",
    yearsExp: 5,
    rating: 4.8,
    specialties: ["Summaries", "Action Items", "Minutes"],
    tasksLabel: "4.5k tasks",
  },
  "customer-support": {
    humanName: "Aisha Rahman",
    title: "Customer Support Lead",
    photoUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=customer-support",
    yearsExp: 7,
    rating: 4.9,
    specialties: ["Ticket Resolution", "Empathy", "SLA"],
    tasksLabel: "5.8k tasks",
  },
  "recruitment-agent": {
    humanName: "Benjamin Okoro",
    title: "Talent Acquisition Specialist",
    photoUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=recruitment-agent",
    yearsExp: 8,
    rating: 4.8,
    specialties: ["Recruiting", "Job Descriptions", "Screening"],
    tasksLabel: "1.9k tasks",
  },
  "legal-advisor": {
    humanName: "Dr. Helena Christou",
    title: "Legal Advisory Specialist",
    photoUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=legal-advisor",
    yearsExp: 12,
    rating: 4.9,
    specialties: ["Contracts", "Compliance", "Legal Review"],
    tasksLabel: "1.4k tasks",
  },
  "cover-letter": {
    humanName: "Olivia Ndegwa",
    title: "Career Documents Expert",
    photoUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=cover-letter",
    yearsExp: 6,
    rating: 4.8,
    specialties: ["Cover Letters", "Resumes", "LinkedIn"],
    tasksLabel: "3.3k tasks",
  },
  "speech-trainer": {
    humanName: "François Dubois",
    title: "Public Speaking Coach",
    photoUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=speech-trainer",
    yearsExp: 9,
    rating: 4.9,
    specialties: ["Speech Writing", "Delivery", "Confidence"],
    tasksLabel: "1.1k tasks",
  },
  "ecommerce-agent": {
    humanName: "Jia Wei",
    title: "E-Commerce Operations Lead",
    photoUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=ecommerce-agent",
    yearsExp: 7,
    rating: 4.8,
    specialties: ["Shopify", "Product Listings", "Conversion"],
    tasksLabel: "2.0k tasks",
  },
  "teaching-agent": {
    humanName: "Dr. Kofi Asare",
    title: "Education Specialist",
    photoUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=teaching-agent",
    yearsExp: 10,
    rating: 4.9,
    specialties: ["Tutoring", "Curriculum", "Explanations"],
    tasksLabel: "3.7k tasks",
  },

  // ── Health & Lifestyle ────────────────────────────────
  "fitness-coach": {
    humanName: "Andre Silva",
    title: "Fitness & Wellness Coach",
    photoUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=fitness-coach",
    yearsExp: 8,
    rating: 4.9,
    specialties: ["Workouts", "Nutrition", "Wellness"],
    tasksLabel: "2.6k tasks",
  },
  "mental-wellbeing": {
    humanName: "Dr. Lina Johansson",
    title: "Mental Wellness Guide",
    photoUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=mental-wellbeing",
    yearsExp: 10,
    rating: 5.0,
    specialties: ["Mindfulness", "Stress Relief", "CBT"],
    tasksLabel: "1.8k tasks",
  },
  "recipe-planner": {
    humanName: "Carmen Reyes",
    title: "Culinary & Recipe Expert",
    photoUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=recipe-planner",
    yearsExp: 7,
    rating: 4.8,
    specialties: ["Meal Planning", "Recipes", "Dietary Needs"],
    tasksLabel: "2.9k tasks",
  },
  "travel-planner": {
    humanName: "Tariq Al-Farsi",
    title: "Travel Planning Specialist",
    photoUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=travel-planner",
    yearsExp: 9,
    rating: 4.9,
    specialties: ["Itineraries", "Budget Travel", "Hidden Gems"],
    tasksLabel: "2.1k tasks",
  },
  "life-coach": {
    humanName: "Nkechi Eze",
    title: "Life & Career Coach",
    photoUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=life-coach",
    yearsExp: 8,
    rating: 4.9,
    specialties: ["Goal Setting", "Habits", "Motivation"],
    tasksLabel: "1.5k tasks",
  },
  "baby-name": {
    humanName: "Elise Fontaine",
    title: "Baby Name Consultant",
    photoUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=baby-name",
    yearsExp: 5,
    rating: 4.8,
    specialties: ["Name Origins", "Meanings", "Trends"],
    tasksLabel: "1.2k tasks",
  },

  // ── Creative & Fun ────────────────────────────────────
  "roast-master": {
    humanName: "Maya Chen",
    title: "Comedy Roast Specialist",
    photoUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=roast-master",
    yearsExp: 7,
    rating: 4.9,
    specialties: ["Comedy", "Improv", "Writing"],
    tasksLabel: "1.8k tasks",
  },
  "dream-interpreter": {
    humanName: "Dr. Surya Bhat",
    title: "Dream Analysis Expert",
    photoUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=dream-interpreter",
    yearsExp: 9,
    rating: 4.8,
    specialties: ["Dream Analysis", "Psychology", "Symbolism"],
    tasksLabel: "1.4k tasks",
  },
  "villain-origin": {
    humanName: "Raven Blackwell",
    title: "Dark Storytelling Writer",
    photoUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=villain-origin",
    yearsExp: 6,
    rating: 4.8,
    specialties: ["Villain Arcs", "Dark Humor", "Fiction"],
    tasksLabel: "1.1k tasks",
  },
  "fortune-teller": {
    humanName: "Celeste Moreno",
    title: "Fortune & Astrology Guide",
    photoUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=fortune-teller",
    yearsExp: 8,
    rating: 4.7,
    specialties: ["Tarot", "Astrology", "Readings"],
    tasksLabel: "2.3k tasks",
  },
  "rap-battle": {
    humanName: "Darius King",
    title: "Rap Battle Lyricist",
    photoUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=rap-battle",
    yearsExp: 6,
    rating: 4.9,
    specialties: ["Rap", "Freestyle", "Wordplay"],
    tasksLabel: "1.6k tasks",
  },
  "alien-anthropologist": {
    humanName: "Dr. Xara Voss",
    title: "Alien Anthropology Specialist",
    photoUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=alien-anthropologist",
    yearsExp: 5,
    rating: 4.7,
    specialties: ["Sci-Fi", "World Building", "Humor"],
    tasksLabel: "670 tasks",
  },
  "toxic-trait": {
    humanName: "Jade Morales",
    title: "Toxic Trait Analyst",
    photoUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=toxic-trait",
    yearsExp: 4,
    rating: 4.8,
    specialties: ["Self-Awareness", "Humor", "Psychology"],
    tasksLabel: "2.0k tasks",
  },
  "dating-profile": {
    humanName: "Leo Andersen",
    title: "Dating Profile Expert",
    photoUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=dating-profile",
    yearsExp: 5,
    rating: 4.8,
    specialties: ["Bios", "Photo Tips", "Conversation"],
    tasksLabel: "1.9k tasks",
  },
  "movie-plot": {
    humanName: "Anya Volkov",
    title: "Movie Plot Creator",
    photoUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=movie-plot",
    yearsExp: 7,
    rating: 4.8,
    specialties: ["Screenwriting", "Plot Twists", "Genre"],
    tasksLabel: "1.3k tasks",
  },
  "song-lyrics": {
    humanName: "Rio Nakamura",
    title: "Songwriting Specialist",
    photoUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=song-lyrics",
    yearsExp: 6,
    rating: 4.8,
    specialties: ["Lyrics", "Melody", "Genres"],
    tasksLabel: "1.7k tasks",
  },
  "bedtime-story": {
    humanName: "Luna Eriksen",
    title: "Children's Story Writer",
    photoUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=bedtime-story",
    yearsExp: 5,
    rating: 4.9,
    specialties: ["Kids Stories", "Fantasy", "Morals"],
    tasksLabel: "2.4k tasks",
  },
  "excuse-generator": {
    humanName: "Felix Hartmann",
    title: "Creative Excuse Specialist",
    photoUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=excuse-generator",
    yearsExp: 3,
    rating: 4.7,
    specialties: ["Excuses", "Comedy", "Persuasion"],
    tasksLabel: "3.1k tasks",
  },
  "apology-writer": {
    humanName: "Sophie Laurent",
    title: "Apology & Diplomacy Expert",
    photoUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=apology-writer",
    yearsExp: 6,
    rating: 4.8,
    specialties: ["Apologies", "Empathy", "Communication"],
    tasksLabel: "1.5k tasks",
  },
  "future-coach": {
    humanName: "Dante Rossi",
    title: "Future Self Coach",
    photoUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=future-coach",
    yearsExp: 7,
    rating: 4.8,
    specialties: ["Visualization", "Goal Planning", "Mindset"],
    tasksLabel: "980 tasks",
  },
  "debate-champion": {
    humanName: "Farah Nasseri",
    title: "Debate & Rhetoric Champion",
    photoUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=debate-champion",
    yearsExp: 8,
    rating: 4.9,
    specialties: ["Debate", "Logic", "Argumentation"],
    tasksLabel: "1.2k tasks",
  },
  "music-generator": {
    humanName: "Soren Nyberg",
    title: "Music Composition Specialist",
    photoUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=music-generator",
    yearsExp: 7,
    rating: 4.8,
    specialties: ["Composition", "Arrangement", "Production"],
    tasksLabel: "890 tasks",
  },
};

export function getAgentPersona(slug: string): AgentPersona | null {
  return PERSONAS[slug] || null;
}
