// Human persona data for agent resume cards
// Maps agent slugs to human-like profile information with cute animal avatars

export interface AgentPersona {
  humanName: string;
  title: string;
  animal: string;        // cute animal emoji
  yearsExp: number;
  rating: number;
  specialties: string[];
  tasksLabel: string;
  about: string;         // short one-liner
}

const PERSONAS: Record<string, AgentPersona> = {
  // ── Product & Engineering ─────────────────────────────
  "startup-idea-gen": {
    humanName: "Arjun Patel",
    title: "Startup Ideation Specialist",
    animal: "\u{1F4A1}",
    yearsExp: 9,
    rating: 4.9,
    specialties: ["Ideation", "Market Fit", "Pitch Decks"],
    tasksLabel: "2.1k tasks",
    about: "Turns wild ideas into fundable startups.",
  },
  "product-launch": {
    humanName: "Sofia Martinez",
    title: "Product Launch Strategist",
    animal: "\u{1F680}",
    yearsExp: 11,
    rating: 4.9,
    specialties: ["Go-to-Market", "Launch Plans", "Growth"],
    tasksLabel: "1.9k tasks",
    about: "Ships products that people actually want.",
  },
  "system-architect": {
    humanName: "Hiroshi Tanaka",
    title: "Systems Architecture Lead",
    animal: "\u{1F427}",
    yearsExp: 12,
    rating: 5.0,
    specialties: ["Architecture", "Scalability", "Cloud"],
    tasksLabel: "3.2k tasks",
    about: "Designs systems that scale to millions.",
  },
  "ux-designer": {
    humanName: "Amara Osei",
    title: "UX Design Expert",
    animal: "\u{1F43B}",
    yearsExp: 8,
    rating: 4.9,
    specialties: ["User Research", "Prototyping", "Design Systems"],
    tasksLabel: "2.4k tasks",
    about: "Makes interfaces feel like magic.",
  },
  "fullstack-developer": {
    humanName: "Liam Chen",
    title: "Full-Stack Developer",
    animal: "\u{1F43C}",
    yearsExp: 10,
    rating: 4.9,
    specialties: ["React", "Node.js", "TypeScript"],
    tasksLabel: "4.1k tasks",
    about: "Creative problem solver, front to back.",
  },
  "python-expert": {
    humanName: "Fatima Al-Rashid",
    title: "Python Engineering Specialist",
    animal: "\u{1F40D}",
    yearsExp: 9,
    rating: 4.8,
    specialties: ["Python", "Data Pipelines", "Automation"],
    tasksLabel: "3.5k tasks",
    about: "Automates everything with elegant Python.",
  },
  "code-reviewer": {
    humanName: "Marcus Johnson",
    title: "Code Quality Analyst",
    animal: "\u{1F989}",
    yearsExp: 11,
    rating: 4.9,
    specialties: ["Code Review", "Best Practices", "Security"],
    tasksLabel: "5.2k tasks",
    about: "Catches bugs before they ship.",
  },
  "debugger": {
    humanName: "Yuki Nakamura",
    title: "Debugging Specialist",
    animal: "\u{1F41B}",
    yearsExp: 7,
    rating: 4.8,
    specialties: ["Debugging", "Performance", "Root Cause"],
    tasksLabel: "2.8k tasks",
    about: "Finds the needle in the stack trace.",
  },
  "sprint-planner": {
    humanName: "Elena Kowalski",
    title: "Agile Sprint Planner",
    animal: "\u{1F420}",
    yearsExp: 8,
    rating: 4.8,
    specialties: ["Scrum", "Sprint Planning", "Velocity"],
    tasksLabel: "1.6k tasks",
    about: "Keeps your sprints on track.",
  },
  "project-planner": {
    humanName: "David Okonkwo",
    title: "Project Management Lead",
    animal: "\u{1F981}",
    yearsExp: 10,
    rating: 4.9,
    specialties: ["Roadmaps", "Resource Planning", "Delivery"],
    tasksLabel: "2.3k tasks",
    about: "Delivers projects on time, every time.",
  },
  "home-renovation": {
    humanName: "Isabella Torres",
    title: "Home Renovation Advisor",
    animal: "\u{1F439}",
    yearsExp: 6,
    rating: 4.7,
    specialties: ["Interior Design", "Budgeting", "Contractors"],
    tasksLabel: "890 tasks",
    about: "Transforms spaces on any budget.",
  },
  "game-design": {
    humanName: "Kai Svensson",
    title: "Game Design Specialist",
    animal: "\u{1F432}",
    yearsExp: 7,
    rating: 4.8,
    specialties: ["Game Mechanics", "Level Design", "Balancing"],
    tasksLabel: "1.2k tasks",
    about: "Designs games people can't put down.",
  },
  "ui-ux-feedback": {
    humanName: "Priya Sharma",
    title: "UI/UX Feedback Analyst",
    animal: "\u{1F431}",
    yearsExp: 6,
    rating: 4.8,
    specialties: ["Usability", "Heuristics", "A/B Testing"],
    tasksLabel: "1.5k tasks",
    about: "Spots UX issues others miss.",
  },
  "devops-agent": {
    humanName: "Omar Hassan",
    title: "DevOps Engineer",
    animal: "\u{1F916}",
    yearsExp: 9,
    rating: 4.9,
    specialties: ["CI/CD", "Docker", "Kubernetes"],
    tasksLabel: "2.7k tasks",
    about: "Automates deploys and infra at scale.",
  },

  // ── Research & Intelligence ───────────────────────────
  "deep-research": {
    humanName: "Dr. Mei Lin",
    title: "Deep Research Analyst",
    animal: "\u{1F9D0}",
    yearsExp: 12,
    rating: 5.0,
    specialties: ["Research", "Synthesis", "Analysis"],
    tasksLabel: "3.8k tasks",
    about: "Goes 10 layers deep on any topic.",
  },
  "academic-researcher": {
    humanName: "Dr. Adaeze Nwosu",
    title: "Academic Research Fellow",
    animal: "\u{1F99C}",
    yearsExp: 10,
    rating: 4.9,
    specialties: ["Literature Review", "Citations", "Methodology"],
    tasksLabel: "2.1k tasks",
    about: "Writes papers that get published.",
  },
  "fact-checker": {
    humanName: "Jonas Eriksson",
    title: "Fact-Checking Specialist",
    animal: "\u{1F50D}",
    yearsExp: 8,
    rating: 4.9,
    specialties: ["Verification", "Sources", "Accuracy"],
    tasksLabel: "4.3k tasks",
    about: "Separates facts from fiction.",
  },
  "startup-trends": {
    humanName: "Zara Ibrahim",
    title: "Startup Trends Analyst",
    animal: "\u{1F98A}",
    yearsExp: 7,
    rating: 4.8,
    specialties: ["Trend Analysis", "VC Insights", "Markets"],
    tasksLabel: "1.4k tasks",
    about: "Spots trends before they go mainstream.",
  },
  "competitor-intel": {
    humanName: "Nikolai Volkov",
    title: "Competitive Intelligence Lead",
    animal: "\u{1F43A}",
    yearsExp: 9,
    rating: 4.9,
    specialties: ["Competitor Analysis", "SWOT", "Strategy"],
    tasksLabel: "1.9k tasks",
    about: "Knows your competitors better than they do.",
  },
  "web-intel": {
    humanName: "Anika Gupta",
    title: "Web Intelligence Specialist",
    animal: "\u{1F577}",
    yearsExp: 6,
    rating: 4.7,
    specialties: ["OSINT", "Web Scraping", "Data Mining"],
    tasksLabel: "2.5k tasks",
    about: "Finds anything on the internet.",
  },
  "data-analyst": {
    humanName: "Rafael Santos",
    title: "Data Analytics Expert",
    animal: "\u{1F42C}",
    yearsExp: 8,
    rating: 4.9,
    specialties: ["SQL", "Statistics", "Dashboards"],
    tasksLabel: "3.1k tasks",
    about: "Turns raw data into clear insights.",
  },
  "visualization-expert": {
    humanName: "Ingrid Bergstr\u00F6m",
    title: "Data Visualization Designer",
    animal: "\u{1F308}",
    yearsExp: 7,
    rating: 4.8,
    specialties: ["Charts", "Infographics", "Storytelling"],
    tasksLabel: "1.7k tasks",
    about: "Makes data beautiful and clear.",
  },
  "strategy-advisor": {
    humanName: "James Okafor",
    title: "Strategy Consultant",
    animal: "\u{1F985}",
    yearsExp: 11,
    rating: 5.0,
    specialties: ["Strategy", "Frameworks", "Growth"],
    tasksLabel: "2.6k tasks",
    about: "Sees the big picture others miss.",
  },
  "decision-helper": {
    humanName: "Clara Johansson",
    title: "Decision Science Specialist",
    animal: "\u{1F3AF}",
    yearsExp: 7,
    rating: 4.8,
    specialties: ["Decision Trees", "Risk Analysis", "Pros/Cons"],
    tasksLabel: "1.3k tasks",
    about: "Helps you make the right call.",
  },
  "vc-due-diligence": {
    humanName: "Alexander Wei",
    title: "Due Diligence Analyst",
    animal: "\u{1F9BE}",
    yearsExp: 10,
    rating: 4.9,
    specialties: ["Due Diligence", "Financials", "Term Sheets"],
    tasksLabel: "980 tasks",
    about: "Vets deals like a top-tier VC.",
  },
  "market-sizing": {
    humanName: "Nadia Petrov",
    title: "Market Sizing Specialist",
    animal: "\u{1F4CA}",
    yearsExp: 8,
    rating: 4.8,
    specialties: ["TAM/SAM/SOM", "Sizing Models", "Research"],
    tasksLabel: "1.1k tasks",
    about: "Sizes any market with precision.",
  },

  // ── Sales & Revenue ───────────────────────────────────
  "sales-rep": {
    humanName: "Carlos Mendoza",
    title: "Sales Development Rep",
    animal: "\u{1F434}",
    yearsExp: 8,
    rating: 4.8,
    specialties: ["Cold Outreach", "Pitching", "Closing"],
    tasksLabel: "3.4k tasks",
    about: "Closes deals that others give up on.",
  },
  "investment-analyst": {
    humanName: "Grace Kimura",
    title: "Investment Research Analyst",
    animal: "\u{1F4B0}",
    yearsExp: 9,
    rating: 4.9,
    specialties: ["Equities", "Valuation", "Portfolio"],
    tasksLabel: "1.8k tasks",
    about: "Finds alpha in any market.",
  },
  "personal-finance": {
    humanName: "Kwame Asante",
    title: "Personal Finance Advisor",
    animal: "\u{1F437}",
    yearsExp: 7,
    rating: 4.8,
    specialties: ["Budgeting", "Investing", "Tax Planning"],
    tasksLabel: "2.2k tasks",
    about: "Grows your wealth, step by step.",
  },
  "real-estate-analyst": {
    humanName: "Leila Ahmadi",
    title: "Real Estate Analyst",
    animal: "\u{1F3E1}",
    yearsExp: 8,
    rating: 4.8,
    specialties: ["Property Analysis", "Market Trends", "ROI"],
    tasksLabel: "1.1k tasks",
    about: "Finds the best deals in real estate.",
  },
  "pricing-strategist": {
    humanName: "Henrik Larsen",
    title: "Pricing Strategy Expert",
    animal: "\u{1F4B8}",
    yearsExp: 9,
    rating: 4.9,
    specialties: ["Pricing Models", "Revenue Ops", "Margins"],
    tasksLabel: "940 tasks",
    about: "Prices products for maximum profit.",
  },
  "proposal-writer": {
    humanName: "Thandiwe Moyo",
    title: "Proposal Writing Specialist",
    animal: "\u{1F4DD}",
    yearsExp: 7,
    rating: 4.8,
    specialties: ["RFPs", "Business Proposals", "Persuasion"],
    tasksLabel: "1.6k tasks",
    about: "Writes proposals that win contracts.",
  },

  // ── Marketing & Content ───────────────────────────────
  "content-creator": {
    humanName: "Maya Rivera",
    title: "Content Creation Lead",
    animal: "\u{1F98B}",
    yearsExp: 8,
    rating: 4.9,
    specialties: ["Copywriting", "Storytelling", "Brand Voice"],
    tasksLabel: "4.7k tasks",
    about: "Creates content that people share.",
  },
  "linkedin-post": {
    humanName: "Daniel Achebe",
    title: "LinkedIn Content Strategist",
    animal: "\u{1F3C6}",
    yearsExp: 6,
    rating: 4.8,
    specialties: ["LinkedIn", "Thought Leadership", "Engagement"],
    tasksLabel: "3.2k tasks",
    about: "Gets your posts to go viral on LinkedIn.",
  },
  "blog-to-podcast": {
    humanName: "Sana Malik",
    title: "Blog-to-Podcast Producer",
    animal: "\u{1F3A7}",
    yearsExp: 5,
    rating: 4.7,
    specialties: ["Podcast Scripts", "Repurposing", "Audio"],
    tasksLabel: "780 tasks",
    about: "Transforms blogs into engaging podcasts.",
  },
  "journalist": {
    humanName: "Thomas Beaumont",
    title: "Investigative Journalist",
    animal: "\u{1F9ED}",
    yearsExp: 10,
    rating: 4.9,
    specialties: ["Reporting", "Interviews", "Long-form"],
    tasksLabel: "1.4k tasks",
    about: "Uncovers the story behind the story.",
  },
  "technical-writer": {
    humanName: "Yuna Park",
    title: "Technical Writing Expert",
    animal: "\u{1F4D6}",
    yearsExp: 8,
    rating: 4.9,
    specialties: ["Documentation", "API Docs", "Tutorials"],
    tasksLabel: "2.9k tasks",
    about: "Makes complex tech simple to understand.",
  },
  "editor": {
    humanName: "Charlotte Duval",
    title: "Senior Editor",
    animal: "\u{1F99A}",
    yearsExp: 11,
    rating: 5.0,
    specialties: ["Editing", "Style Guide", "Clarity"],
    tasksLabel: "5.1k tasks",
    about: "Polishes every word to perfection.",
  },
  "email-drafter": {
    humanName: "Ahmed Benali",
    title: "Email Marketing Specialist",
    animal: "\u{1F4E8}",
    yearsExp: 6,
    rating: 4.8,
    specialties: ["Email Campaigns", "Subject Lines", "CTAs"],
    tasksLabel: "3.6k tasks",
    about: "Writes emails people actually open.",
  },
  "meme-caption": {
    humanName: "Zoe Chang",
    title: "Meme & Caption Creator",
    animal: "\u{1F92A}",
    yearsExp: 4,
    rating: 4.7,
    specialties: ["Memes", "Viral Content", "Humor"],
    tasksLabel: "2.8k tasks",
    about: "Makes the internet laugh on command.",
  },
  "seo-agent": {
    humanName: "Viktor Novak",
    title: "SEO Optimization Expert",
    animal: "\u{1F50E}",
    yearsExp: 8,
    rating: 4.9,
    specialties: ["SEO", "Keywords", "Ranking Strategy"],
    tasksLabel: "2.3k tasks",
    about: "Gets you to page one of Google.",
  },
  "social-media": {
    humanName: "Amira Diallo",
    title: "Social Media Strategist",
    animal: "\u{1F525}",
    yearsExp: 7,
    rating: 4.8,
    specialties: ["Social Strategy", "Engagement", "Analytics"],
    tasksLabel: "3.9k tasks",
    about: "Builds audiences that convert.",
  },
  "ad-copy": {
    humanName: "Lucas Moreau",
    title: "Ad Copywriter",
    animal: "\u{1F4E2}",
    yearsExp: 7,
    rating: 4.8,
    specialties: ["Ad Copy", "Headlines", "Conversion"],
    tasksLabel: "2.1k tasks",
    about: "Writes ads that print money.",
  },
  "newsletter-agent": {
    humanName: "Rina Takahashi",
    title: "Newsletter Curator",
    animal: "\u{1F4F0}",
    yearsExp: 5,
    rating: 4.7,
    specialties: ["Newsletters", "Curation", "Retention"],
    tasksLabel: "1.5k tasks",
    about: "Curates newsletters people subscribe to.",
  },
  "video-script": {
    humanName: "Mateo Vargas",
    title: "Video Script Writer",
    animal: "\u{1F3AC}",
    yearsExp: 6,
    rating: 4.8,
    specialties: ["Video Scripts", "YouTube", "Hooks"],
    tasksLabel: "1.8k tasks",
    about: "Scripts videos that keep viewers hooked.",
  },

  // ── Operations & Productivity ─────────────────────────
  "general-assistant": {
    humanName: "Emma Lindqvist",
    title: "Executive Assistant",
    animal: "\u{1F43E}",
    yearsExp: 8,
    rating: 4.9,
    specialties: ["Task Management", "Research", "Writing"],
    tasksLabel: "6.2k tasks",
    about: "Your reliable right hand for anything.",
  },
  "meeting-notes": {
    humanName: "Samuel Mensah",
    title: "Meeting Notes Specialist",
    animal: "\u{1F4CB}",
    yearsExp: 5,
    rating: 4.8,
    specialties: ["Summaries", "Action Items", "Minutes"],
    tasksLabel: "4.5k tasks",
    about: "Never miss a key takeaway again.",
  },
  "customer-support": {
    humanName: "Aisha Rahman",
    title: "Customer Support Lead",
    animal: "\u{1F49B}",
    yearsExp: 7,
    rating: 4.9,
    specialties: ["Ticket Resolution", "Empathy", "SLA"],
    tasksLabel: "5.8k tasks",
    about: "Turns upset customers into fans.",
  },
  "recruitment-agent": {
    humanName: "Benjamin Okoro",
    title: "Talent Acquisition Specialist",
    animal: "\u{1F331}",
    yearsExp: 8,
    rating: 4.8,
    specialties: ["Recruiting", "Job Descriptions", "Screening"],
    tasksLabel: "1.9k tasks",
    about: "Finds the perfect hire, fast.",
  },
  "legal-advisor": {
    humanName: "Dr. Helena Christou",
    title: "Legal Advisory Specialist",
    animal: "\u{2696}\uFE0F",
    yearsExp: 12,
    rating: 4.9,
    specialties: ["Contracts", "Compliance", "Legal Review"],
    tasksLabel: "1.4k tasks",
    about: "Protects you from legal headaches.",
  },
  "cover-letter": {
    humanName: "Olivia Ndegwa",
    title: "Career Documents Expert",
    animal: "\u{2728}",
    yearsExp: 6,
    rating: 4.8,
    specialties: ["Cover Letters", "Resumes", "LinkedIn"],
    tasksLabel: "3.3k tasks",
    about: "Gets you interviews at dream companies.",
  },
  "speech-trainer": {
    humanName: "Fran\u00E7ois Dubois",
    title: "Public Speaking Coach",
    animal: "\u{1F3A4}",
    yearsExp: 9,
    rating: 4.9,
    specialties: ["Speech Writing", "Delivery", "Confidence"],
    tasksLabel: "1.1k tasks",
    about: "Turns nervous speakers into captivating ones.",
  },
  "ecommerce-agent": {
    humanName: "Jia Wei",
    title: "E-Commerce Operations Lead",
    animal: "\u{1F6D2}",
    yearsExp: 7,
    rating: 4.8,
    specialties: ["Shopify", "Product Listings", "Conversion"],
    tasksLabel: "2.0k tasks",
    about: "Optimizes stores for maximum revenue.",
  },
  "teaching-agent": {
    humanName: "Dr. Kofi Asare",
    title: "Education Specialist",
    animal: "\u{1F393}",
    yearsExp: 10,
    rating: 4.9,
    specialties: ["Tutoring", "Curriculum", "Explanations"],
    tasksLabel: "3.7k tasks",
    about: "Explains anything so it clicks.",
  },

  // ── Health & Lifestyle ────────────────────────────────
  "fitness-coach": {
    humanName: "Andre Silva",
    title: "Fitness & Wellness Coach",
    animal: "\u{1F4AA}",
    yearsExp: 8,
    rating: 4.9,
    specialties: ["Workouts", "Nutrition", "Wellness"],
    tasksLabel: "2.6k tasks",
    about: "Gets you in the best shape of your life.",
  },
  "mental-wellbeing": {
    humanName: "Dr. Lina Johansson",
    title: "Mental Wellness Guide",
    animal: "\u{1F33F}",
    yearsExp: 10,
    rating: 5.0,
    specialties: ["Mindfulness", "Stress Relief", "CBT"],
    tasksLabel: "1.8k tasks",
    about: "A calm, caring guide for your mind.",
  },
  "recipe-planner": {
    humanName: "Carmen Reyes",
    title: "Culinary & Recipe Expert",
    animal: "\u{1F9D1}\u200D\u{1F373}",
    yearsExp: 7,
    rating: 4.8,
    specialties: ["Meal Planning", "Recipes", "Dietary Needs"],
    tasksLabel: "2.9k tasks",
    about: "Plans delicious meals for any diet.",
  },
  "travel-planner": {
    humanName: "Tariq Al-Farsi",
    title: "Travel Planning Specialist",
    animal: "\u{2708}\uFE0F",
    yearsExp: 9,
    rating: 4.9,
    specialties: ["Itineraries", "Budget Travel", "Hidden Gems"],
    tasksLabel: "2.1k tasks",
    about: "Plans trips you'll never forget.",
  },
  "life-coach": {
    humanName: "Nkechi Eze",
    title: "Life & Career Coach",
    animal: "\u{1F31F}",
    yearsExp: 8,
    rating: 4.9,
    specialties: ["Goal Setting", "Habits", "Motivation"],
    tasksLabel: "1.5k tasks",
    about: "Helps you become your best self.",
  },
  "baby-name": {
    humanName: "Elise Fontaine",
    title: "Baby Name Consultant",
    animal: "\u{1F476}",
    yearsExp: 5,
    rating: 4.8,
    specialties: ["Name Origins", "Meanings", "Trends"],
    tasksLabel: "1.2k tasks",
    about: "Finds the perfect name for your little one.",
  },

  // ── Creative & Fun ────────────────────────────────────
  "roast-master": {
    humanName: "Maya Chen",
    title: "Comedy Roast Specialist",
    animal: "\u{1F525}",
    yearsExp: 7,
    rating: 4.9,
    specialties: ["Comedy", "Improv", "Writing"],
    tasksLabel: "1.8k tasks",
    about: "Delivers savage burns with love.",
  },
  "dream-interpreter": {
    humanName: "Dr. Surya Bhat",
    title: "Dream Analysis Expert",
    animal: "\u{1F319}",
    yearsExp: 9,
    rating: 4.8,
    specialties: ["Dream Analysis", "Psychology", "Symbolism"],
    tasksLabel: "1.4k tasks",
    about: "Decodes what your dreams really mean.",
  },
  "villain-origin": {
    humanName: "Raven Blackwell",
    title: "Dark Storytelling Writer",
    animal: "\u{1F9DB}",
    yearsExp: 6,
    rating: 4.8,
    specialties: ["Villain Arcs", "Dark Humor", "Fiction"],
    tasksLabel: "1.1k tasks",
    about: "Writes origin stories for your inner villain.",
  },
  "fortune-teller": {
    humanName: "Celeste Moreno",
    title: "Fortune & Astrology Guide",
    animal: "\u{1F52E}",
    yearsExp: 8,
    rating: 4.7,
    specialties: ["Tarot", "Astrology", "Readings"],
    tasksLabel: "2.3k tasks",
    about: "Reads your future in the stars.",
  },
  "rap-battle": {
    humanName: "Darius King",
    title: "Rap Battle Lyricist",
    animal: "\u{1F3A4}",
    yearsExp: 6,
    rating: 4.9,
    specialties: ["Rap", "Freestyle", "Wordplay"],
    tasksLabel: "1.6k tasks",
    about: "Drops bars that leave crowds speechless.",
  },
  "alien-anthropologist": {
    humanName: "Dr. Xara Voss",
    title: "Alien Anthropology Specialist",
    animal: "\u{1F47D}",
    yearsExp: 5,
    rating: 4.7,
    specialties: ["Sci-Fi", "World Building", "Humor"],
    tasksLabel: "670 tasks",
    about: "Studies humans from an alien perspective.",
  },
  "toxic-trait": {
    humanName: "Jade Morales",
    title: "Toxic Trait Analyst",
    animal: "\u{1F480}",
    yearsExp: 4,
    rating: 4.8,
    specialties: ["Self-Awareness", "Humor", "Psychology"],
    tasksLabel: "2.0k tasks",
    about: "Calls out your toxic traits with love.",
  },
  "dating-profile": {
    humanName: "Leo Andersen",
    title: "Dating Profile Expert",
    animal: "\u{1F498}",
    yearsExp: 5,
    rating: 4.8,
    specialties: ["Bios", "Photo Tips", "Conversation"],
    tasksLabel: "1.9k tasks",
    about: "Gets you more matches, guaranteed.",
  },
  "movie-plot": {
    humanName: "Anya Volkov",
    title: "Movie Plot Creator",
    animal: "\u{1F3AC}",
    yearsExp: 7,
    rating: 4.8,
    specialties: ["Screenwriting", "Plot Twists", "Genre"],
    tasksLabel: "1.3k tasks",
    about: "Creates movie plots Hollywood would buy.",
  },
  "song-lyrics": {
    humanName: "Rio Nakamura",
    title: "Songwriting Specialist",
    animal: "\u{1F3B5}",
    yearsExp: 6,
    rating: 4.8,
    specialties: ["Lyrics", "Melody", "Genres"],
    tasksLabel: "1.7k tasks",
    about: "Writes songs that get stuck in your head.",
  },
  "bedtime-story": {
    humanName: "Luna Eriksen",
    title: "Children's Story Writer",
    animal: "\u{1F43B}\u200D\u2744\uFE0F",
    yearsExp: 5,
    rating: 4.9,
    specialties: ["Kids Stories", "Fantasy", "Morals"],
    tasksLabel: "2.4k tasks",
    about: "Writes stories kids beg to hear again.",
  },
  "excuse-generator": {
    humanName: "Felix Hartmann",
    title: "Creative Excuse Specialist",
    animal: "\u{1F92B}",
    yearsExp: 3,
    rating: 4.7,
    specialties: ["Excuses", "Comedy", "Persuasion"],
    tasksLabel: "3.1k tasks",
    about: "Generates excuses no one can argue with.",
  },
  "apology-writer": {
    humanName: "Sophie Laurent",
    title: "Apology & Diplomacy Expert",
    animal: "\u{1F54A}\uFE0F",
    yearsExp: 6,
    rating: 4.8,
    specialties: ["Apologies", "Empathy", "Communication"],
    tasksLabel: "1.5k tasks",
    about: "Writes apologies that actually heal.",
  },
  "future-coach": {
    humanName: "Dante Rossi",
    title: "Future Self Coach",
    animal: "\u{1F680}",
    yearsExp: 7,
    rating: 4.8,
    specialties: ["Visualization", "Goal Planning", "Mindset"],
    tasksLabel: "980 tasks",
    about: "Helps you design your future self.",
  },
  "debate-champion": {
    humanName: "Farah Nasseri",
    title: "Debate & Rhetoric Champion",
    animal: "\u{1F945}",
    yearsExp: 8,
    rating: 4.9,
    specialties: ["Debate", "Logic", "Argumentation"],
    tasksLabel: "1.2k tasks",
    about: "Wins any argument with style.",
  },
  "music-generator": {
    humanName: "Soren Nyberg",
    title: "Music Composition Specialist",
    animal: "\u{1F3B6}",
    yearsExp: 7,
    rating: 4.8,
    specialties: ["Composition", "Arrangement", "Production"],
    tasksLabel: "890 tasks",
    about: "Composes music that moves people.",
  },
};

export function getAgentPersona(slug: string): AgentPersona | null {
  return PERSONAS[slug] || null;
}
