// Human persona data for agent resume cards
// Maps agent slugs to human-like profile information with cute animal avatars

export interface AgentPersona {
  humanName: string;
  title: string;
  animal: string;        // cute animal emoji
  yearsExp: number;
  rating: number;
  specialties: string[];
  tasksLabel: string;
  about: string;         // short one-liner
}

const PERSONAS: Record<string, AgentPersona> = {
  // ── Product & Engineering ─────────────────────────────
  "startup-idea-gen": {
    humanName: "Arjun Patel",
    title: "Startup Ideation Specialist",
    animal: "\u{1F4A1}",
    yearsExp: 9,
    rating: 4.9,
    specialties: ["Ideation", "Market Fit", "Pitch Decks"],
    tasksLabel: "2.1k tasks",
    about: "Turns wild ideas into fundable startups.",
  },
  "product-launch": {
    humanName: "Sofia Martinez",
    title: "Product Launch Strategist",
    animal: "\u{1F680}",
    yearsExp: 11,
    rating: 4.9,
    specialties: ["Go-to-Market", "Launch Plans", "Growth"],
    tasksLabel: "1.9k tasks",
    about: "Ships products that people actually want.",
  },
  "system-architect": {
    humanName: "Hiroshi Tanaka",
    title: "Systems Architecture Lead",
    animal: "\u{1F427}",
    yearsExp: 12,
    rating: 5.0,
    specialties: ["Architecture", "Scalability", "Cloud"],
    tasksLabel: "3.2k tasks",
    about: "Designs systems that scale to millions.",
  },
  "ux-designer": {
    humanName: "Amara Osei",
    title: "UX Design Expert",
    animal: "\u{1F43B}",
    yearsExp: 8,
    rating: 4.9,
    specialties: ["User Research", "Prototyping", "Design Systems"],
    tasksLabel: "2.4k tasks",
    about: "Makes interfaces feel like magic.",
  },
  "fullstack-developer": {
    humanName: "Liam Chen",
    title: "Full-Stack Developer",
    animal: "\u{1F43C}",
    yearsExp: 10,
    rating: 4.9,
    specialties: ["React", "Node.js", "TypeScript"],
    tasksLabel: "4.1k tasks",
    about: "Creative problem solver, front to back.",
  },
  "python-expert": {
    humanName: "Fatima Al-Rashid",
    title: "Python Engineering Specialist",
    animal: "\u{1F40D}",
    yearsExp: 9,
    rating: 4.8,
    specialties: ["Python", "Data Pipelines", "Automation"],
    tasksLabel: "3.5k tasks",
    about: "Automates everything with elegant Python.",
  },
  "code-reviewer": {
    humanName: "Marcus Johnson",
    title: "Code Quality Analyst",
    animal: "\u{1F989}",
    yearsExp: 11,
    rating: 4.9,
    specialties: ["Code Review", "Best Practices", "Security"],
    tasksLabel: "5.2k tasks",
    about: "Catches bugs before they ship.",
  },
  "debugger": {
    humanName: "Yuki Nakamura",
    title: "Debugging Specialist",
    animal: "\u{1F41B}",
    yearsExp: 7,
    rating: 4.8,
    specialties: ["Debugging", "Performance", "Root Cause"],
    tasksLabel: "2.8k tasks",
    about: "Finds the needle in the stack trace.",
  },
  "sprint-planner": {
    humanName: "Elena Kowalski",
    title: "Agile Sprint Planner",
    animal: "\u{1F420}",
    yearsExp: 8,
    rating: 4.8,
    specialties: ["Scrum", "Sprint Planning", "Velocity"],
    tasksLabel: "1.6k tasks",
    about: "Keeps your sprints on track.",
  },
  "project-planner": {
    humanName: "David Okonkwo",
    title: "Project Management Lead",
    animal: "\u{1F981}",
    yearsExp: 10,
    rating: 4.9,
    specialties: ["Roadmaps", "Resource Planning", "Delivery"],
    tasksLabel: "2.3k tasks",
    about: "Delivers projects on time, every time.",
  },
  "devops-agent": {
    humanName: "Omar Hassan",
    title: "DevOps Engineer",
    animal: "\u{1F916}",
    yearsExp: 9,
    rating: 4.9,
    specialties: ["CI/CD", "Docker", "Kubernetes"],
    tasksLabel: "2.7k tasks",
    about: "Automates deploys and infra at scale.",
  },

  // ── Research & Intelligence ───────────────────────────
  "deep-research": {
    humanName: "Dr. Mei Lin",
    title: "Deep Research Analyst",
    animal: "\u{1F9D0}",
    yearsExp: 12,
    rating: 5.0,
    specialties: ["Research", "Synthesis", "Analysis"],
    tasksLabel: "3.8k tasks",
    about: "Goes 10 layers deep on any topic.",
  },
  "academic-researcher": {
    humanName: "Dr. Adaeze Nwosu",
    title: "Academic Research Fellow",
    animal: "\u{1F99C}",
    yearsExp: 10,
    rating: 4.9,
    specialties: ["Literature Review", "Citations", "Methodology"],
    tasksLabel: "2.1k tasks",
    about: "Writes papers that get published.",
  },
  "fact-checker": {
    humanName: "Jonas Eriksson",
    title: "Fact-Checking Specialist",
    animal: "\u{1F50D}",
    yearsExp: 8,
    rating: 4.9,
    specialties: ["Verification", "Sources", "Accuracy"],
    tasksLabel: "4.3k tasks",
    about: "Separates facts from fiction.",
  },
  "startup-trends": {
    humanName: "Zara Ibrahim",
    title: "Startup Trends Analyst",
    animal: "\u{1F98A}",
    yearsExp: 7,
    rating: 4.8,
    specialties: ["Trend Analysis", "VC Insights", "Markets"],
    tasksLabel: "1.4k tasks",
    about: "Spots trends before they go mainstream.",
  },
  "competitor-intel": {
    humanName: "Nikolai Volkov",
    title: "Competitive Intelligence Lead",
    animal: "\u{1F43A}",
    yearsExp: 9,
    rating: 4.9,
    specialties: ["Competitor Analysis", "SWOT", "Strategy"],
    tasksLabel: "1.9k tasks",
    about: "Knows your competitors better than they do.",
  },
  "web-intel": {
    humanName: "Anika Gupta",
    title: "Web Intelligence Specialist",
    animal: "\u{1F577}",
    yearsExp: 6,
    rating: 4.7,
    specialties: ["OSINT", "Web Scraping", "Data Mining"],
    tasksLabel: "2.5k tasks",
    about: "Finds anything on the internet.",
  },
  "data-analyst": {
    humanName: "Rafael Santos",
    title: "Data Analytics Expert",
    animal: "\u{1F42C}",
    yearsExp: 8,
    rating: 4.9,
    specialties: ["SQL", "Statistics", "Dashboards"],
    tasksLabel: "3.1k tasks",
    about: "Turns raw data into clear insights.",
  },
  "visualization-expert": {
    humanName: "Ingrid Bergstr\u00F6m",
    title: "Data Visualization Designer",
    animal: "\u{1F308}",
    yearsExp: 7,
    rating: 4.8,
    specialties: ["Charts", "Infographics", "Storytelling"],
    tasksLabel: "1.7k tasks",
    about: "Makes data beautiful and clear.",
  },
  "strategy-advisor": {
    humanName: "James Okafor",
    title: "Strategy Consultant",
    animal: "\u{1F985}",
    yearsExp: 11,
    rating: 5.0,
    specialties: ["Strategy", "Frameworks", "Growth"],
    tasksLabel: "2.6k tasks",
    about: "Sees the big picture others miss.",
  },
  "decision-helper": {
    humanName: "Clara Johansson",
    title: "Decision Science Specialist",
    animal: "\u{1F3AF}",
    yearsExp: 7,
    rating: 4.8,
    specialties: ["Decision Trees", "Risk Analysis", "Pros/Cons"],
    tasksLabel: "1.3k tasks",
    about: "Helps you make the right call.",
  },
  "vc-due-diligence": {
    humanName: "Alexander Wei",
    title: "Due Diligence Analyst",
    animal: "\u{1F9BE}",
    yearsExp: 10,
    rating: 4.9,
    specialties: ["Due Diligence", "Financials", "Term Sheets"],
    tasksLabel: "980 tasks",
    about: "Vets deals like a top-tier VC.",
  },
  "market-sizing": {
    humanName: "Nadia Petrov",
    title: "Market Sizing Specialist",
    animal: "\u{1F4CA}",
    yearsExp: 8,
    rating: 4.8,
    specialties: ["TAM/SAM/SOM", "Sizing Models", "Research"],
    tasksLabel: "1.1k tasks",
    about: "Sizes any market with precision.",
  },

  // ── Sales & Revenue ───────────────────────────────────
  "sales-rep": {
    humanName: "Carlos Mendoza",
    title: "Sales Development Rep",
    animal: "\u{1F434}",
    yearsExp: 8,
    rating: 4.8,
    specialties: ["Cold Outreach", "Pitching", "Closing"],
    tasksLabel: "3.4k tasks",
    about: "Closes deals that others give up on.",
  },
  "investment-analyst": {
    humanName: "Grace Kimura",
    title: "Investment Research Analyst",
    animal: "\u{1F4B0}",
    yearsExp: 9,
    rating: 4.9,
    specialties: ["Equities", "Valuation", "Portfolio"],
    tasksLabel: "1.8k tasks",
    about: "Finds alpha in any market.",
  },
  "personal-finance": {
    humanName: "Kwame Asante",
    title: "Personal Finance Advisor",
    animal: "\u{1F437}",
    yearsExp: 7,
    rating: 4.8,
    specialties: ["Budgeting", "Investing", "Tax Planning"],
    tasksLabel: "2.2k tasks",
    about: "Grows your wealth, step by step.",
  },
  "pricing-strategist": {
    humanName: "Henrik Larsen",
    title: "Pricing Strategy Expert",
    animal: "\u{1F4B8}",
    yearsExp: 9,
    rating: 4.9,
    specialties: ["Pricing Models", "Revenue Ops", "Margins"],
    tasksLabel: "940 tasks",
    about: "Prices products for maximum profit.",
  },
  "proposal-writer": {
    humanName: "Thandiwe Moyo",
    title: "Proposal Writing Specialist",
    animal: "\u{1F4DD}",
    yearsExp: 7,
    rating: 4.8,
    specialties: ["RFPs", "Business Proposals", "Persuasion"],
    tasksLabel: "1.6k tasks",
    about: "Writes proposals that win contracts.",
  },

  // ── Marketing & Content ───────────────────────────────
  "content-creator": {
    humanName: "Maya Rivera",
    title: "Content Creation Lead",
    animal: "\u{1F98B}",
    yearsExp: 8,
    rating: 4.9,
    specialties: ["Copywriting", "Storytelling", "Brand Voice"],
    tasksLabel: "4.7k tasks",
    about: "Creates content that people share.",
  },
  "linkedin-post": {
    humanName: "Daniel Achebe",
    title: "LinkedIn Content Strategist",
    animal: "\u{1F3C6}",
    yearsExp: 6,
    rating: 4.8,
    specialties: ["LinkedIn", "Thought Leadership", "Engagement"],
    tasksLabel: "3.2k tasks",
    about: "Gets your posts to go viral on LinkedIn.",
  },
  "blog-to-podcast": {
    humanName: "Sana Malik",
    title: "Blog-to-Podcast Producer",
    animal: "\u{1F3A7}",
    yearsExp: 5,
    rating: 4.7,
    specialties: ["Podcast Scripts", "Repurposing", "Audio"],
    tasksLabel: "780 tasks",
    about: "Transforms blogs into engaging podcasts.",
  },
  "journalist": {
    humanName: "Thomas Beaumont",
    title: "Investigative Journalist",
    animal: "\u{1F9ED}",
    yearsExp: 10,
    rating: 4.9,
    specialties: ["Reporting", "Interviews", "Long-form"],
    tasksLabel: "1.4k tasks",
    about: "Uncovers the story behind the story.",
  },
  "technical-writer": {
    humanName: "Yuna Park",
    title: "Technical Writing Expert",
    animal: "\u{1F4D6}",
    yearsExp: 8,
    rating: 4.9,
    specialties: ["Documentation", "API Docs", "Tutorials"],
    tasksLabel: "2.9k tasks",
    about: "Makes complex tech simple to understand.",
  },
  "editor": {
    humanName: "Charlotte Duval",
    title: "Senior Editor",
    animal: "\u{1F99A}",
    yearsExp: 11,
    rating: 5.0,
    specialties: ["Editing", "Style Guide", "Clarity"],
    tasksLabel: "5.1k tasks",
    about: "Polishes every word to perfection.",
  },
  "email-drafter": {
    humanName: "Ahmed Benali",
    title: "Email Marketing Specialist",
    animal: "\u{1F4E8}",
    yearsExp: 6,
    rating: 4.8,
    specialties: ["Email Campaigns", "Subject Lines", "CTAs"],
    tasksLabel: "3.6k tasks",
    about: "Writes emails people actually open.",
  },
  "seo-agent": {
    humanName: "Viktor Novak",
    title: "SEO Optimization Expert",
    animal: "\u{1F50E}",
    yearsExp: 8,
    rating: 4.9,
    specialties: ["SEO", "Keywords", "Ranking Strategy"],
    tasksLabel: "2.3k tasks",
    about: "Gets you to page one of Google.",
  },
  "social-media": {
    humanName: "Amira Diallo",
    title: "Social Media Strategist",
    animal: "\u{1F525}",
    yearsExp: 7,
    rating: 4.8,
    specialties: ["Social Strategy", "Engagement", "Analytics"],
    tasksLabel: "3.9k tasks",
    about: "Builds audiences that convert.",
  },
  "ad-copy": {
    humanName: "Lucas Moreau",
    title: "Ad Copywriter",
    animal: "\u{1F4E2}",
    yearsExp: 7,
    rating: 4.8,
    specialties: ["Ad Copy", "Headlines", "Conversion"],
    tasksLabel: "2.1k tasks",
    about: "Writes ads that print money.",
  },
  "newsletter-agent": {
    humanName: "Rina Takahashi",
    title: "Newsletter Curator",
    animal: "\u{1F4F0}",
    yearsExp: 5,
    rating: 4.7,
    specialties: ["Newsletters", "Curation", "Retention"],
    tasksLabel: "1.5k tasks",
    about: "Curates newsletters people subscribe to.",
  },
  "video-script": {
    humanName: "Mateo Vargas",
    title: "Video Script Writer",
    animal: "\u{1F3AC}",
    yearsExp: 6,
    rating: 4.8,
    specialties: ["Video Scripts", "YouTube", "Hooks"],
    tasksLabel: "1.8k tasks",
    about: "Scripts videos that keep viewers hooked.",
  },

  // ── Operations & Productivity ─────────────────────────
  "general-assistant": {
    humanName: "Emma Lindqvist",
    title: "Executive Assistant",
    animal: "\u{1F43E}",
    yearsExp: 8,
    rating: 4.9,
    specialties: ["Task Management", "Research", "Writing"],
    tasksLabel: "6.2k tasks",
    about: "Your reliable right hand for anything.",
  },
  "meeting-notes": {
    humanName: "Samuel Mensah",
    title: "Meeting Notes Specialist",
    animal: "\u{1F4CB}",
    yearsExp: 5,
    rating: 4.8,
    specialties: ["Summaries", "Action Items", "Minutes"],
    tasksLabel: "4.5k tasks",
    about: "Never miss a key takeaway again.",
  },
  "customer-support": {
    humanName: "Aisha Rahman",
    title: "Customer Support Lead",
    animal: "\u{1F49B}",
    yearsExp: 7,
    rating: 4.9,
    specialties: ["Ticket Resolution", "Empathy", "SLA"],
    tasksLabel: "5.8k tasks",
    about: "Turns upset customers into fans.",
  },
  "recruitment-agent": {
    humanName: "Benjamin Okoro",
    title: "Talent Acquisition Specialist",
    animal: "\u{1F331}",
    yearsExp: 8,
    rating: 4.8,
    specialties: ["Recruiting", "Job Descriptions", "Screening"],
    tasksLabel: "1.9k tasks",
    about: "Finds the perfect hire, fast.",
  },
  "legal-advisor": {
    humanName: "Dr. Helena Christou",
    title: "Legal Advisory Specialist",
    animal: "\u{2696}\uFE0F",
    yearsExp: 12,
    rating: 4.9,
    specialties: ["Contracts", "Compliance", "Legal Review"],
    tasksLabel: "1.4k tasks",
    about: "Protects you from legal headaches.",
  },
  "cover-letter": {
    humanName: "Olivia Ndegwa",
    title: "Career Documents Expert",
    animal: "\u{2728}",
    yearsExp: 6,
    rating: 4.8,
    specialties: ["Cover Letters", "Resumes", "LinkedIn"],
    tasksLabel: "3.3k tasks",
    about: "Gets you interviews at dream companies.",
  },

  // ── Health & Lifestyle ────────────────────────────────
  "fitness-coach": {
    humanName: "Andre Silva",
    title: "Fitness & Wellness Coach",
    animal: "\u{1F4AA}",
    yearsExp: 8,
    rating: 4.9,
    specialties: ["Workouts", "Nutrition", "Wellness"],
    tasksLabel: "2.6k tasks",
    about: "Gets you in the best shape of your life.",
  },
  "mental-wellbeing": {
    humanName: "Dr. Lina Johansson",
    title: "Mental Wellness Guide",
    animal: "\u{1F33F}",
    yearsExp: 10,
    rating: 5.0,
    specialties: ["Mindfulness", "Stress Relief", "CBT"],
    tasksLabel: "1.8k tasks",
    about: "A calm, caring guide for your mind.",
  },
  "recipe-planner": {
    humanName: "Carmen Reyes",
    title: "Culinary & Recipe Expert",
    animal: "\u{1F9D1}\u200D\u{1F373}",
    yearsExp: 7,
    rating: 4.8,
    specialties: ["Meal Planning", "Recipes", "Dietary Needs"],
    tasksLabel: "2.9k tasks",
    about: "Plans delicious meals for any diet.",
  },
  "travel-planner": {
    humanName: "Tariq Al-Farsi",
    title: "Travel Planning Specialist",
    animal: "\u{2708}\uFE0F",
    yearsExp: 9,
    rating: 4.9,
    specialties: ["Itineraries", "Budget Travel", "Hidden Gems"],
    tasksLabel: "2.1k tasks",
    about: "Plans trips you'll never forget.",
  },

  // ── Creative & Fun ────────────────────────────────────
  "roast-master": {
    humanName: "Maya Chen",
    title: "Comedy Roast Specialist",
    animal: "\u{1F525}",
    yearsExp: 7,
    rating: 4.9,
    specialties: ["Comedy", "Improv", "Writing"],
    tasksLabel: "1.8k tasks",
    about: "Delivers savage burns with love.",
  },
  "song-lyrics": {
    humanName: "Rio Nakamura",
    title: "Songwriting Specialist",
    animal: "\u{1F3B5}",
    yearsExp: 6,
    rating: 4.8,
    specialties: ["Lyrics", "Melody", "Genres"],
    tasksLabel: "1.7k tasks",
    about: "Writes songs that get stuck in your head.",
  },

  // ── Career & Job Search ────────────────────────────────
  "job-hunter": {
    humanName: "Priya Sharma",
    title: "Job Search Strategist",
    animal: "\u{1F3AF}",
    yearsExp: 8,
    rating: 4.9,
    specialties: ["Job Search", "Networking", "Market Research"],
    tasksLabel: "2.8k tasks",
    about: "Finds jobs others miss.",
  },
  "auto-applier": {
    humanName: "Jordan Blake",
    title: "Application Specialist",
    animal: "\u{1F4DD}",
    yearsExp: 6,
    rating: 4.8,
    specialties: ["Cover Letters", "Applications", "Tailoring"],
    tasksLabel: "3.1k tasks",
    about: "Crafts applications that get callbacks.",
  },
  "resume-optimizer": {
    humanName: "Michelle Torres",
    title: "Resume & ATS Expert",
    animal: "\u{1F4C4}",
    yearsExp: 9,
    rating: 4.9,
    specialties: ["ATS", "Keywords", "Resume Design"],
    tasksLabel: "4.2k tasks",
    about: "Gets your resume past the robots.",
  },
  "interview-coach": {
    humanName: "Derek Washington",
    title: "Interview Prep Coach",
    animal: "\u{1F3A4}",
    yearsExp: 10,
    rating: 4.9,
    specialties: ["STAR Method", "Mock Interviews", "Company Research"],
    tasksLabel: "2.4k tasks",
    about: "Turns nervous candidates into confident closers.",
  },
  "salary-negotiator": {
    humanName: "Ananya Desai",
    title: "Compensation Strategist",
    animal: "\u{1F4B0}",
    yearsExp: 11,
    rating: 5.0,
    specialties: ["Salary Data", "Negotiation", "Total Comp"],
    tasksLabel: "1.9k tasks",
    about: "Gets you the salary you deserve.",
  },

  // ── Money & Bills ────────────────────────────────
  "subscription-killer": {
    humanName: "Ryan Kowalski",
    title: "Subscription Audit Specialist",
    animal: "\u{2702}\uFE0F",
    yearsExp: 5,
    rating: 4.8,
    specialties: ["Subscriptions", "Savings", "Alternatives"],
    tasksLabel: "3.6k tasks",
    about: "Finds the subscriptions draining your wallet.",
  },
  "bill-negotiator": {
    humanName: "Keisha Williams",
    title: "Bill Negotiation Expert",
    animal: "\u{1F4DE}",
    yearsExp: 7,
    rating: 4.9,
    specialties: ["Negotiation", "Scripts", "Savings"],
    tasksLabel: "2.7k tasks",
    about: "Talks your bills down, guaranteed.",
  },
  "tax-deduction-finder": {
    humanName: "Victor Chen",
    title: "Tax Savings Researcher",
    animal: "\u{1F9FE}",
    yearsExp: 9,
    rating: 4.9,
    specialties: ["Deductions", "Credits", "Tax Strategy"],
    tasksLabel: "1.8k tasks",
    about: "Finds money the IRS owes you.",
  },
  "credit-score-coach": {
    humanName: "Destiny Johnson",
    title: "Credit Improvement Specialist",
    animal: "\u{1F4CA}",
    yearsExp: 7,
    rating: 4.8,
    specialties: ["Credit Repair", "Score Building", "Debt Strategy"],
    tasksLabel: "2.1k tasks",
    about: "Builds credit scores that open doors.",
  },
  "deal-spotter": {
    humanName: "Marco Rossi",
    title: "Deal Hunting Expert",
    animal: "\u{1F3F7}\uFE0F",
    yearsExp: 6,
    rating: 4.8,
    specialties: ["Price Tracking", "Coupons", "Deal Timing"],
    tasksLabel: "4.5k tasks",
    about: "Never pays full price for anything.",
  },

  // ── Legal & Rights ────────────────────────────────
  "dispute-fighter": {
    humanName: "Serena Blackwell",
    title: "Consumer Dispute Specialist",
    animal: "\u{2694}\uFE0F",
    yearsExp: 8,
    rating: 4.9,
    specialties: ["Dispute Letters", "Consumer Rights", "Escalation"],
    tasksLabel: "1.6k tasks",
    about: "Fights for your consumer rights.",
  },
  "benefits-finder": {
    humanName: "Maria Gonzalez",
    title: "Benefits Navigator",
    animal: "\u{1F50E}",
    yearsExp: 7,
    rating: 4.8,
    specialties: ["Government Programs", "Eligibility", "Applications"],
    tasksLabel: "2.3k tasks",
    about: "Finds benefits you didn't know existed.",
  },
  "lease-reviewer": {
    humanName: "Nathan Park",
    title: "Lease Analysis Specialist",
    animal: "\u{1F3E0}",
    yearsExp: 8,
    rating: 4.9,
    specialties: ["Lease Terms", "Tenant Rights", "Red Flags"],
    tasksLabel: "1.4k tasks",
    about: "Reads the fine print so you don't have to.",
  },
  "immigration-helper": {
    humanName: "Fatou Diallo",
    title: "Immigration Research Specialist",
    animal: "\u{1F30D}",
    yearsExp: 9,
    rating: 4.9,
    specialties: ["Visa Research", "Immigration Paths", "Documentation"],
    tasksLabel: "1.7k tasks",
    about: "Navigates complex immigration pathways.",
  },
  "small-claims-advisor": {
    humanName: "Robert Castellano",
    title: "Small Claims Guide",
    animal: "\u{2696}\uFE0F",
    yearsExp: 10,
    rating: 4.9,
    specialties: ["Small Claims", "Court Filing", "Evidence"],
    tasksLabel: "980 tasks",
    about: "Makes small claims court less intimidating.",
  },

  // ── Housing & Moving ────────────────────────────────
  "apartment-scout": {
    humanName: "Jasmine Liu",
    title: "Apartment Search Expert",
    animal: "\u{1F3E2}",
    yearsExp: 7,
    rating: 4.8,
    specialties: ["Neighborhoods", "Market Research", "Rentals"],
    tasksLabel: "2.5k tasks",
    about: "Finds apartments that match your vibe.",
  },
  "moving-coordinator": {
    humanName: "Chris Anderson",
    title: "Relocation Planner",
    animal: "\u{1F4E6}",
    yearsExp: 8,
    rating: 4.9,
    specialties: ["Moving Plans", "Checklists", "Cost Estimates"],
    tasksLabel: "1.9k tasks",
    about: "Makes moving day stress-free.",
  },
  "utility-optimizer": {
    humanName: "Sam Patel",
    title: "Utility Comparison Expert",
    animal: "\u{26A1}",
    yearsExp: 6,
    rating: 4.8,
    specialties: ["Plan Comparison", "Internet", "Energy"],
    tasksLabel: "2.2k tasks",
    about: "Finds the best plan at the lowest price.",
  },
  // ── Health & Medical ────────────────────────────────
  "medical-bill-auditor": {
    humanName: "Patricia Nguyen",
    title: "Medical Billing Analyst",
    animal: "\u{1F3E5}",
    yearsExp: 9,
    rating: 4.9,
    specialties: ["Billing Codes", "Appeals", "Negotiation"],
    tasksLabel: "1.5k tasks",
    about: "Catches billing errors others miss.",
  },
  "insurance-comparer": {
    humanName: "David Kim",
    title: "Insurance Analyst",
    animal: "\u{1F6E1}\uFE0F",
    yearsExp: 8,
    rating: 4.8,
    specialties: ["Plan Comparison", "Coverage Analysis", "Premiums"],
    tasksLabel: "1.8k tasks",
    about: "Finds the right coverage at the right price.",
  },
  "symptom-researcher": {
    humanName: "Dr. Sarah Mitchell",
    title: "Health Information Researcher",
    animal: "\u{1FA7A}",
    yearsExp: 11,
    rating: 4.9,
    specialties: ["Medical Research", "Symptom Analysis", "Doctor Prep"],
    tasksLabel: "2.6k tasks",
    about: "Helps you walk into the doctor prepared.",
  },
  "prescription-saver": {
    humanName: "Lisa Thompson",
    title: "Rx Savings Specialist",
    animal: "\u{1F48A}",
    yearsExp: 7,
    rating: 4.8,
    specialties: ["Drug Pricing", "Discount Programs", "Generics"],
    tasksLabel: "2.0k tasks",
    about: "Slashes prescription costs dramatically.",
  },

  // ── Education ────────────────────────────────
  "scholarship-hunter": {
    humanName: "Amira Hassan",
    title: "Scholarship Research Expert",
    animal: "\u{1F393}",
    yearsExp: 8,
    rating: 4.9,
    specialties: ["Scholarships", "Financial Aid", "Applications"],
    tasksLabel: "2.3k tasks",
    about: "Finds free money for your education.",
  },
  "college-advisor": {
    humanName: "Prof. James Wright",
    title: "College Admissions Advisor",
    animal: "\u{1F3EB}",
    yearsExp: 12,
    rating: 5.0,
    specialties: ["Admissions", "Program Research", "School Fit"],
    tasksLabel: "1.6k tasks",
    about: "Guides you to the right school.",
  },

  // ── Smart Shopping ────────────────────────────────
  "return-assistant": {
    humanName: "Karen Chen",
    title: "Returns & Refunds Expert",
    animal: "\u{1F4EC}",
    yearsExp: 5,
    rating: 4.8,
    specialties: ["Return Policies", "Refund Requests", "Consumer Rights"],
    tasksLabel: "3.4k tasks",
    about: "Gets your money back, hassle-free.",
  },
  "car-buy-negotiator": {
    humanName: "Tony Russo",
    title: "Auto Purchase Negotiator",
    animal: "\u{1F697}",
    yearsExp: 10,
    rating: 4.9,
    specialties: ["Car Pricing", "Dealer Tactics", "Negotiation"],
    tasksLabel: "1.3k tasks",
    about: "Saves thousands on your next car.",
  },

  // ── Freelance & Side Income ────────────────────────────────
  "freelance-bid-writer": {
    humanName: "Diana Okafor",
    title: "Freelance Proposal Expert",
    animal: "\u{270D}\uFE0F",
    yearsExp: 7,
    rating: 4.8,
    specialties: ["Proposals", "Upwork", "Client Messaging"],
    tasksLabel: "2.8k tasks",
    about: "Writes proposals that win projects.",
  },
  "side-hustle-matcher": {
    humanName: "Jake Morrison",
    title: "Side Income Strategist",
    animal: "\u{1F680}",
    yearsExp: 6,
    rating: 4.8,
    specialties: ["Side Hustles", "Passive Income", "Skill Monetization"],
    tasksLabel: "2.1k tasks",
    about: "Turns your skills into income streams.",
  },
  "contract-reviewer": {
    humanName: "Elena Vasquez",
    title: "Contract Analysis Specialist",
    animal: "\u{1F4CB}",
    yearsExp: 9,
    rating: 4.9,
    specialties: ["Contract Law", "Red Flags", "Negotiation Points"],
    tasksLabel: "1.5k tasks",
    about: "Protects you from bad contracts.",
  },
};

export function getAgentPersona(slug: string): AgentPersona | null {
  return PERSONAS[slug] || null;
}
