import { NextRequest, NextResponse } from "next/server";
import { getTask, getAgent, updateTask, mockSteps } from "@/lib/mock-data";
import type { TaskStep } from "@/lib/types/task";

// Demo mode: simulate agent execution with a mock streaming response
export async function POST(
  _request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id } = await params;
  const task = getTask(id);
  if (!task) return NextResponse.json({ error: "Not found" }, { status: 404 });
  if (!task.agent_id) return NextResponse.json({ error: "No agent assigned" }, { status: 400 });

  const agent = getAgent(task.agent_id);
  if (!agent) return NextResponse.json({ error: "Agent not found" }, { status: 404 });

  // Set to working
  updateTask(id, {
    status: "working",
    progress: 5,
    started_at: new Date().toISOString(),
    current_step: `${agent.name} is analyzing the task`,
  });

  // Create steps
  const steps: TaskStep[] = [
    { id: `s-${id}-1`, task_id: id, step_number: 1, description: `${agent.name} is analyzing the task`, status: "working", started_at: new Date().toISOString(), completed_at: null, tokens_used: 0 },
    { id: `s-${id}-2`, task_id: id, step_number: 2, description: "Gathering relevant information", status: "pending", started_at: null, completed_at: null, tokens_used: 0 },
    { id: `s-${id}-3`, task_id: id, step_number: 3, description: "Processing and generating output", status: "pending", started_at: null, completed_at: null, tokens_used: 0 },
    { id: `s-${id}-4`, task_id: id, step_number: 4, description: "Finalizing results", status: "pending", started_at: null, completed_at: null, tokens_used: 0 },
  ];
  mockSteps.set(id, steps);

  // Simulate async work — after a delay, complete the task
  simulateAgentWork(id, agent.name, steps);

  return NextResponse.json({ status: "started" });
}

async function simulateAgentWork(taskId: string, agentName: string, steps: TaskStep[]) {
  const task = getTask(taskId);
  if (!task) return;

  // Step 1: Analyzing (1s)
  await delay(1000);
  steps[0].status = "done";
  steps[0].completed_at = new Date().toISOString();
  steps[0].tokens_used = 245;
  steps[1].status = "working";
  steps[1].started_at = new Date().toISOString();
  updateTask(taskId, { progress: 25, current_step: "Gathering relevant information" });

  // Step 2: Gathering (1.5s)
  await delay(1500);
  steps[1].status = "done";
  steps[1].completed_at = new Date().toISOString();
  steps[1].tokens_used = 512;
  steps[2].status = "working";
  steps[2].started_at = new Date().toISOString();
  updateTask(taskId, { progress: 50, current_step: "Processing and generating output" });

  // Step 3: Processing (2s)
  await delay(2000);
  steps[2].status = "done";
  steps[2].completed_at = new Date().toISOString();
  steps[2].tokens_used = 1834;
  steps[3].status = "working";
  steps[3].started_at = new Date().toISOString();
  updateTask(taskId, { progress: 80, current_step: "Finalizing results" });

  // Step 4: Finalizing (1s)
  await delay(1000);
  steps[3].status = "done";
  steps[3].completed_at = new Date().toISOString();
  steps[3].tokens_used = 389;

  // Generate demo output based on task title
  const output = generateDemoOutput(task.title, agentName);
  const totalTokensIn = 890;
  const totalTokensOut = 2980;
  const cost = (totalTokensIn * 3.0 + totalTokensOut * 15.0) / 1_000_000;

  updateTask(taskId, {
    status: "review",
    progress: 100,
    output,
    cost_usd: cost,
    tokens_in: totalTokensIn,
    tokens_out: totalTokensOut,
    duration_seconds: 6,
    current_step: "Complete — ready for your review",
  });
}

function generateDemoOutput(title: string, agentName: string): string {
  return `# ${title}

## Summary
${agentName} has completed the analysis of this task. Here are the key findings and deliverables.

## Key Findings

1. **Primary Insight** — The task has been thoroughly analyzed and the results show promising outcomes that align with the project goals.

2. **Supporting Data** — Based on the research conducted:
   - Point A demonstrates strong performance metrics
   - Point B highlights areas for improvement
   - Point C suggests a clear path forward

3. **Comparative Analysis**

| Aspect | Current | Proposed | Impact |
|--------|---------|----------|--------|
| Efficiency | 65% | 88% | +23% |
| Coverage | 72% | 95% | +23% |
| Quality | 80% | 92% | +12% |

## Recommendations

- **Short-term**: Focus on the highest-impact items identified above
- **Medium-term**: Build on the foundation with iterative improvements
- **Long-term**: Scale the approach across the organization

## Next Steps

1. Review these findings and provide feedback
2. Prioritize the recommended actions
3. Set up follow-up tasks for implementation

> *This analysis was generated by ${agentName}. Review the output and approve or request revisions.*`;
}

function delay(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}
